# English words that have clear visual representations.
# Used to filter out abstract words before fetching images.

CONCRETE_WORDS = {
    # ── Animals ───────────────────────────────────────────────────────
    "dog", "cat", "bird", "fish", "horse", "cow", "pig", "sheep", "goat",
    "chicken", "duck", "turkey", "rabbit", "mouse", "rat", "hamster",
    "elephant", "lion", "tiger", "bear", "wolf", "fox", "deer", "monkey",
    "gorilla", "zebra", "giraffe", "hippo", "rhino", "crocodile", "alligator",
    "snake", "lizard", "turtle", "frog", "toad", "shark", "whale", "dolphin",
    "octopus", "crab", "lobster", "shrimp", "butterfly", "bee", "ant",
    "spider", "fly", "mosquito", "worm", "eagle", "owl", "parrot", "penguin",
    "flamingo", "peacock", "rooster", "chick", "blowfish", "snail", "bug",
    "caterpillar", "scorpion", "bat", "panda", "koala", "kangaroo", "hedgehog",
    "otter", "skunk", "raccoon", "sloth", "mammoth", "bison", "ox", "camel",
    "llama", "swan", "bunny",

    # ── Food & drink ──────────────────────────────────────────────────
    "apple", "banana", "orange", "lemon", "lime", "grape", "strawberry",
    "watermelon", "mango", "pineapple", "peach", "pear", "cherry", "plum",
    "avocado", "tomato", "coconut", "kiwi", "melon", "blueberry",
    "potato", "onion", "garlic", "carrot", "pepper", "eggplant", "aubergine",
    "lettuce", "spinach", "broccoli", "mushroom", "corn", "rice", "bean",
    "cucumber", "pumpkin",
    "bread", "cheese", "butter", "milk", "egg", "meat", "beef", "pork",
    "chicken", "fish", "shrimp", "bacon", "hotdog", "hot dog", "sausage",
    "pasta", "pizza", "burger", "hamburger", "sandwich",
    "soup", "salad", "taco", "burrito", "sushi", "ramen", "curry", "fries",
    "pancake", "waffle", "croissant", "doughnut", "donut", "bagel", "pretzel",
    "cake", "cookie", "cookies", "chocolate", "candy", "lollipop", "ice cream",
    "coffee", "tea", "juice", "water", "wine", "beer", "cocktail", "soda",
    "champagne", "smoothie", "lemonade",

    # ── Body parts ────────────────────────────────────────────────────
    "hand", "hands", "foot", "feet", "head", "eye", "eyes", "ear", "nose",
    "mouth", "lip", "lips", "tooth", "teeth", "tongue", "hair", "face",
    "cheek", "chin", "neck", "shoulder", "arm", "elbow", "wrist", "finger",
    "thumb", "chest", "stomach", "belly", "back", "hip", "leg", "knee",
    "ankle", "toe", "heart", "brain", "lung", "lungs", "bone", "muscle", "skin", "nail",

    # ── People & roles ────────────────────────────────────────────────
    "man", "woman", "boy", "girl", "baby", "child", "teenager", "adult",
    "person", "family", "mother", "mom", "father", "dad", "sister", "brother",
    "grandmother", "grandma", "grandfather", "grandpa", "couple", "twins",
    "friend", "doctor", "nurse", "teacher", "student",
    "police", "cop", "soldier", "firefighter", "farmer", "chef", "cook",
    "waiter", "driver", "pilot", "sailor", "mechanic", "scientist", "artist",
    "singer", "judge", "detective", "king", "queen", "prince", "princess",
    "guard", "hero", "villain",

    # ── Clothing & accessories ────────────────────────────────────────
    "shirt", "tshirt", "dress", "skirt", "pants", "jeans", "shorts", "jacket",
    "coat", "sweater", "hoodie", "bikini", "shoes", "sneakers", "boots",
    "sandals", "sandal", "socks", "sock", "hat", "cap", "crown", "scarf",
    "gloves", "glove", "tie", "necktie", "belt", "bag", "handbag", "purse",
    "backpack", "glasses", "sunglasses", "ring", "necklace", "earring",
    "watch", "umbrella", "ribbon",

    # ── Transport ─────────────────────────────────────────────────────
    "car", "automobile", "bus", "train", "plane", "airplane", "boat", "ship",
    "bicycle", "bike", "motorbike", "motorcycle", "truck", "van", "taxi",
    "cab", "helicopter", "submarine", "rocket", "tractor", "ambulance",
    "fire truck", "firetruck", "scooter", "skateboard", "ferry", "speedboat",
    "canoe", "monorail", "trolley",

    # ── Buildings & places ────────────────────────────────────────────
    "house", "home", "apartment", "building", "school", "hospital", "church",
    "mosque", "temple", "shrine", "bank", "hotel", "restaurant", "cafe", "bar",
    "shop", "store", "market", "supermarket", "pharmacy", "library",
    "museum", "cinema", "theater", "stadium", "gym", "pool", "park",
    "beach", "airport", "station", "port", "bridge", "tower", "castle",
    "prison", "factory", "farm", "garden", "playground", "office",

    # ── Nature & environment ──────────────────────────────────────────
    "tree", "palm tree", "cactus", "bamboo", "flower", "grass", "herb",
    "plant", "bush", "forest", "jungle", "mountain", "hill", "valley",
    "river", "lake", "sea", "ocean", "beach", "desert", "island", "volcano",
    "cave", "waterfall", "earth", "globe", "world", "comet",
    "sun", "moon", "star", "cloud", "rain", "snow", "lightning", "thunder",
    "rainbow", "wind", "storm", "tornado", "hurricane", "fire", "rock",
    "stone", "sand", "mud", "night", "sunset", "sunrise",
    "rose", "daisy", "tulip", "sunflower", "blossom", "leaf", "leaves", "seed",
    "snowman", "snowflake",

    # ── Home & furniture ──────────────────────────────────────────────
    "door", "window", "wall", "floor", "ceiling", "roof", "stairs",
    "table", "chair", "sofa", "couch", "bed", "desk", "shelf",
    "wardrobe", "drawer", "lamp", "mirror", "carpet", "curtain",
    "kitchen", "bathroom", "bedroom", "living room", "toilet", "shower",
    "bath", "bathtub", "sink", "stove", "oven", "fridge", "refrigerator",
    "washing machine", "broom", "basket", "razor", "lotion",

    # ── Numbers ───────────────────────────────────────────────────────
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
    "zero", "one", "two", "three", "four", "five",
    "six", "seven", "eight", "nine", "ten",

    # ── Gifts & celebrations ──────────────────────────────────────────
    "gift", "present", "birthday", "party", "cake", "balloon", "candle",
    "celebration", "anniversary", "wedding",

    # ── Objects & tools ───────────────────────────────────────────────
    "photo", "photos", "picture", "image", "selfie",
    "book", "books", "pen", "pencil", "paper", "notebook", "phone", "telephone",
    "computer", "laptop", "keyboard", "screen", "camera", "television", "tv",
    "radio", "clock", "alarm", "key", "lock", "bottle", "cup", "mug", "glass",
    "plate", "bowl", "spoon", "fork", "knife", "pan", "pot", "box", "ball",
    "toy", "doll", "teddy bear", "gun", "sword", "dagger", "hammer", "saw",
    "wrench", "screwdriver", "nail", "screw", "rope", "ladder", "brush",
    "paintbrush", "comb", "toothbrush", "towel", "soap", "candle", "lamp",
    "flashlight", "torch", "map", "flag", "coin", "money", "cash", "card",
    "letter", "envelope", "stamp", "ticket", "scissors", "magnifier",
    "telescope", "microscope", "syringe", "pill", "pills", "bandage",
    "trophy", "medal", "gem", "crystal", "diamond", "kite", "yarn",
    "thread", "needle", "magnet", "battery", "lightbulb", "bulb",

    # ── Sports & activities ───────────────────────────────────────────
    "football", "soccer", "basketball", "tennis", "baseball", "softball",
    "volleyball", "rugby", "golf", "bowling", "cricket", "hockey",
    "swimming", "cycling", "biking", "running", "walking", "hiking",
    "climbing", "boxing", "wrestling", "skiing", "snowboarding", "surfing",
    "skating", "yoga", "dance", "dancing", "gymnastics", "archery", "fishing",
    "hunting", "skateboarding", "martial arts", "karate", "fencing",
    "rowing", "parachute", "diving", "lacrosse", "weightlifting",

    # ── Concrete action verbs ─────────────────────────────────────────
    "look", "watch", "see", "hear", "listen",
    "run", "walk", "jump", "swim", "fly", "climb", "crawl", "roll",
    "fall", "stand", "sit", "lie", "kneel", "bend", "stretch", "spin",
    "eat", "drink", "cook", "cut", "slice", "chop", "fry", "bake",
    "boil", "grill", "pour", "stir", "wash", "clean", "sweep", "mop",
    "sleep", "wake", "yawn", "sneeze", "cough", "breathe", "blink",
    "smile", "laugh", "cry", "shout", "whisper", "sing", "scream",
    "kiss", "hug", "wave", "point", "clap", "snap", "scratch", "punch",
    "kick", "push", "pull", "lift", "carry", "throw", "catch", "drop",
    "hit", "shoot", "fight", "chase", "hide", "dig", "plant", "water",
    "drive", "ride", "sail", "fly", "park", "brake", "accelerate",
    "write", "draw", "paint", "type", "read", "print", "cut", "paste",
    "build", "break", "fix", "open", "close", "lock", "unlock", "tie",
    "untie", "wrap", "unwrap", "fill", "empty", "light", "blow", "burn",
    "spray", "iron", "sew", "knit", "fold", "hang", "stack", "pack",

    # ── Colours ───────────────────────────────────────────────────────
    "color", "colour",
    "red", "blue", "green", "yellow", "orange", "purple", "pink",
    "white", "black", "brown", "grey", "gold", "silver",

    # ── Weather & sky ─────────────────────────────────────────────────
    "sunny", "cloudy", "rainy", "snowy", "windy", "foggy", "thunder",
    "lightning", "rainbow", "sunset", "sunrise",

    # ── Entertainment ─────────────────────────────────────────────────
    "movie", "movies", "film", "films", "cinema",
    "music", "song", "songs", "concert", "album",
    "game", "games", "video game",
    "television", "show", "series", "episode",
    "ticket", "entrance",
    "popcorn",

    # ── Work & everyday ───────────────────────────────────────────────
    "work", "job", "office", "meeting",
    "internet", "web", "website",
    "cellular", "mobile",
    "silence", "noise",
    "yes", "no",
    "like", "love", "hate",
    "good", "great", "excellent", "fantastic", "perfect", "wonderful",
    "amazing", "incredible", "awesome", "superb", "magnificent",
    "bad", "terrible", "horrible", "awful", "dreadful", "evil",

    # ── Characters & roles ────────────────────────────────────────────
    "spy", "pirate", "robot", "alien", "monster", "ghost", "witch",
    "hero", "villain", "ninja", "zombie",

    # ── Events & disasters ────────────────────────────────────────────
    "earthquake", "tsunami", "flood", "hurricane", "tornado",
    "disaster", "accident", "explosion", "war", "battle",

    # ── Emotions with clear visual expression ─────────────────────────
    "happy", "sad", "angry", "scared", "surprised", "disgusted",
    "confused", "excited", "bored", "tired", "crying", "laughing",
    "sleeping", "thinking", "nervous", "worried", "shocked", "cool",
    "embarrassed", "jealous", "proud", "hurt", "silly", "crazy", "sick",

    # ── Descriptive adjectives with visual representations ────────────
    "expensive", "cheap", "free",
    "big", "large", "huge", "giant", "enormous",
    "small", "tiny", "little", "mini",
    "fast", "quick", "slow",
    "hot", "cold", "warm", "freezing",
    "new", "old", "ancient",
    "clean", "dirty",
    "full", "empty",
    "heavy", "light",
    "loud", "quiet",
    "beautiful", "pretty", "ugly",
    "strong", "weak",
    "rich", "poor",
    "dark", "bright",
    "wet", "dry",
    "sharp", "broken", "lost", "found",
    "soft", "hard", "smooth", "rough",
    "healthy", "dead", "alive", "hidden", "visible", "open", "closed",

    # ── Abstract but picturable ───────────────────────────────────────
    "speak", "talk", "say", "think",
    "sound", "noise", "silence",
    "time", "idea", "question", "answer", "problem", "danger", "warning",
    "peace", "death", "magic", "spell", "dream",
    "stop", "go", "sleep", "eat", "drink",
    "meeting", "internet", "web", "website",

    # ── Countries & nationalities ─────────────────────────────────────
    "spain", "spanish", "spaniard",
    "japan", "japanese",
    "united states", "usa", "american",
    "united kingdom", "british", "england", "english", "scotland", "scottish",
    "wales", "welsh",
    "france", "french",
    "germany", "german",
    "italy", "italian",
    "china", "chinese",
    "brazil", "brazilian",
    "argentina", "argentinian", "argentine",
    "mexico", "mexican",
    "portugal", "portuguese",
    "russia", "russian",
    "south korea", "korea", "korean",
    "india", "indian",
    "australia", "australian",
    "canada", "canadian",
    "chile", "chilean",
    "peru", "peruvian",
    "cuba", "cuban",
    "venezuela", "venezuelan",
    "colombia", "colombian",
    "costa rica", "costa rican",
    "ecuador", "ecuadorian",
    "paraguay", "paraguayan",
    "uruguay", "uruguayan",
    "bolivia", "bolivian",
    "honduras", "honduran",
    "guatemala", "guatemalan",
    "el salvador", "salvadoran",
    "nicaragua", "nicaraguan",
    "panama", "panamanian",
    "dominican republic", "dominican",
    "puerto rico", "puerto rican",
    "netherlands", "dutch", "holland",
    "greece", "greek",
    "sweden", "swedish",
    "norway", "norwegian",
    "denmark", "danish",
    "finland", "finnish",
    "poland", "polish",
    "turkey", "turkish",
    "saudi arabia", "saudi",
    "egypt", "egyptian",
    "morocco", "moroccan",
    "south africa", "south african",
    "nigeria", "nigerian",
    "ukraine", "ukrainian",
    "israel", "israeli",
    "iran", "iranian",
    "iraq", "iraqi",
    "pakistan", "pakistani",
    "indonesia", "indonesian",
    "philippines", "filipino", "philippine",
    "thailand", "thai",
    "vietnam", "vietnamese",
    "new zealand", "new zealander",
    "ireland", "irish",
    "switzerland", "swiss",
    "belgium", "belgian",
    "austria", "austrian",
    "czech republic", "czech",
    "romania", "romanian",
    "hungary", "hungarian",
    "serbia", "serbian",

    # ── Fantasy & characters ──────────────────────────────────────────
    "pirate", "robot", "alien", "monster", "ghost", "witch", "hero",
    "villain", "ninja", "zombie", "vampire", "mermaid", "fairy",
    "angel", "devil", "clown",
}

